export const randomPhrases = [
  "Una sorpresa agradable llegará cuando menos lo esperes",
  "La constancia de hoy será tu recompensa de mañana",
  "Algo bueno está tomando forma para ti",
  "La suerte favorece a quien no se rinde",
  "Un pequeño gesto abrirá una gran oportunidad",
  "Confía en el proceso, vas por buen camino",
  "Lo que buscas también te está buscando",
  "Un cambio positivo comienza con una decisión simple",
  "La paciencia traerá noticias favorables",
  "Hoy siembras, pronto recogerás",
  "Una sonrisa sincera atraerá buena fortuna",
  "El esfuerzo silencioso dará frutos visibles",
  "Una respuesta llegará cuando estés listo",
  "La calma te permitirá ver la oportunidad",
  "Algo inesperado mejorará tu día",
  "Cada paso firme te acerca a algo mejor",
  "La buena fortuna acompaña a los perseverantes",
  "Un nuevo comienzo se presenta discretamente",
  "La confianza abrirá la puerta correcta",
  "El momento indicado está más cerca de lo que crees",
];
